# Generated by Django 6.0.3 on 2026-03-22 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='created_by_id',
            new_name='created_by',
        ),
    ]
