# Generated by Django 6.0.3 on 2026-03-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_created_by_id_quiz_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='questions',
        ),
    ]
