# Generated by Django 6.0.3 on 2026-03-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_question_question_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questions',
            new_name='question',
        ),
    ]
